### ISSUE TITLE
Documentation update: Use DynamicProperties to show that dynamic properties have different variable scopes

### ISSUE THREAD

**Issue by sgsabbage** [marklogic/nifi#110]
Hi folks,

Something I caught while reading the code is that both the meta and property dynamic properties evaluate flowfile attributes: https://github.com/marklogic/nifi/blob/88341593832017a606228ab2ab9bc98f18425e78/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/PutMarkLogic.java#L496-L510

However, the DynamicProperty annotation covers all properties in one go, and so shows that the language scope is VARIABLE_REGISTRY only:

https://github.com/marklogic/nifi/blob/88341593832017a606228ab2ab9bc98f18425e78/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/PutMarkLogic.java#L75-L78

I believe it would be possible to use the DynamicProperties annotation to split these apart and make their use clearer, e.g as in the PutFTP processor:

https://github.com/apache/nifi/blob/e4b7e47836edf47042973e604005058c28eed23b/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutFTP.java#L50-L60

**Comment by rjrudin** [comment]
Thanks for the idea, this seems like the right approach.

**Comment by rjrudin** [comment]
@sgsabbage Do you know where the info from a DynamicProperty is actually shown in NiFi? There's an overridden getSupportedDynamicPropertyDescriptor method in AbstractMarkLogicProcessor that NiFi uses for showing a description of a dynamic property that's been added to the processor. I'm using NiFi 1.9.x, but I would figure that the name/value/description from DynamicProperty has value somewhere, I just can't find it.

**Comment by sgsabbage** [comment]
@rjrudin sorry for the delay on getting back to you. Best I can tell is that the `@DynamicProperties` annotation is used to provide the   documentation for the Usage page, e.g. 
![image](https://user-images.githubusercontent.com/1389994/114837970-2683e780-9dcc-11eb-863b-7ee47ac4b93c.png)
while the `getSupportedDynamicPropertyDescriptor` function is used when viewing the properties in the processor, e.g.

![image](https://user-images.githubusercontent.com/1389994/114838188-5a5f0d00-9dcc-11eb-8d7e-3e137cd248d5.png)

**Comment by rjrudin** [comment]
Thanks - I verified that the getSupportedDynamicPropertyDescriptor method is returning correct descriptions, including the correct expression language scope.
