### ISSUE TITLE
ML Nifi does not support datahub 5.4 and Hub Central conversion

### ISSUE THREAD

**Issue by mchiarelli** [marklogic/nifi#111]
Updating from 5.2 to 5.4 and converting for Hub Central. For RunFlowMarkLogic I get:

{
  "jobId" : "a50394af-a9f0-4457-8624-202d40dcfc1e",
  "jobStatus" : "failed",
  "lastAttemptedStep" : null,
  "lastCompletedStep" : null,
  "user" : null,
  "stepResponses" : {
    "2" : {
      "flowName" : "ingestOffice",
      "stepName" : null,
      "stepDefinitionName" : null,
      "stepDefinitionType" : null,
      "stepOutput" : [ "java.lang.NullPointerException\r\n\tat com.marklogic.hub.step.MarkLogicStepDefinitionProvider.getStepDefinition(MarkLogicStepDefinitionProvider.java:20)\r\n\tat com.marklogic.hub.step.StepRunnerFactory.getStepRunner(StepRunnerFactory.java:41)\r\n\tat com.marklogic.hub.flow.impl.FlowRunnerImpl$FlowRunnerTask.run(FlowRunnerImpl.java:310)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n" ],
      "fullOutput" : null,
      "status" : "failed step 2",
      "totalEvents" : 0,
      "successfulEvents" : 0,
      "failedEvents" : 0,
      "successfulBatches" : 0,
      "failedBatches" : 0,
      "success" : false,
      "stepStartTime" : null,
      "stepEndTime" : null
    }
  },
  "timeEnded" : null,
  "flow" : "ingestOffice",
  "timeStarted" : null
}

**Comment by RobertSzkutak** [comment]
+1 I also have a customer who wants this

**Comment by rjrudin** [comment]
Just confirming I got the same thing. We'll get a bugfix release out soon for this.

**Comment by rjrudin** [comment]
Upgrading RunFlowMarkLogic to use the DHF 5.4 library took care of the fix; manually tested it against the reference-entity-model project in DHF.
