### ISSUE TITLE
PutMarkLogic sometimes stops running when there are still flow files available

### ISSUE THREAD

**Issue by dmcassel** [marklogic/nifi#112]
After processing a large number of flow files, PutMarkLogic will sometimes stop running with a few left in the queue. PutMarkLogic has already requested them from the queue (they won't show up when asking NiFi to show the list of flow files in the queue), but just sits on them. Stopping PutMarkLogic triggers the `@OnStopped` event, calling the `completeWriteBatcherJob` method and finishing them up. 

When Concurrent Tasks is greater than 1, it's possible that `shouldFlushIfEmpty` can end up false when the `writeBatcher` has unsent documents. When the processor gets stopped, the `writeBatcher` gets flushed and all's well.

I think we could address that using synchronized blocks when accessing or changing `shouldFlushIfEmpty`, right?

**Comment by rjrudin** [comment]
shouldFlushIfEmpty does look like the culprit here. I think converting it to an AtomicBoolean should do the trick, and then the state in PutMarkLogic is all concurrent-friendly.

**Comment by rjrudin** [comment]
@dmcassel  Thoughts on a good test case here? I have a fairly simple test where I have a GenerateFlowFile processor that spits out 200 flowfiles at a time, running every 1 second. I then have a PutML that writes to ML, and I configured that with a concurrency of 3 tasks. I let that flow run for awhile, then I stop GenerateFF and wait to see if everything gets flushed to ML.

With the change to AtomicBoolean, I still see FFs not getting written. I think there's still the problem of "shouldFlushIfEmpty" being a shared resource - I think it needs to somehow be associated with each task that's created for the processor. 

Alternatively, we could always flush when FF is null in PutML, as I don't think there's any real penalty to that. The "context.yield()" call is what gives the user control over how often that happens by configuring "Yield Duration" on the processor. Thoughts on that?

**Comment by rjrudin** [comment]
Okay, now I'm pretty sure that shouldFlushIfEmpty is unnecessary and that context.yield() is all we need. Going to do the following:

- Remove shouldFlushIfEmpty
- Add info logging for when PutML calls context.yield(), just so it's obvious in the logs that it's happening

This means every time the PutML processor is invoked, it will do an async flush of the WriteBatcher. When it has zero docs, that's pretty much an instantaneous operation. Then it will yield, and the user can configure how long that takes.

**Comment by dmcassel** [comment]
Doing an asynch flush every time sounds great to me. Nice and reliable and it sounds like it's fast.

**Comment by dmcassel** [comment]
@rjrudin I see you closed this ticket and that it was assigned to the 1.9.1.6 milestone. Any ETA on that release?

**Comment by rjrudin** [comment]
Hopefully today.

**Comment by rjrudin** [comment]
@dmcassel  Release is out at https://github.com/marklogic/nifi/releases/tag/1.9.1.6 - please open a new bug if you still see FlowFiles getting "stuck", though I'm fairly confident via testing that the above solution does the trick here.

**Comment by dmcassel** [comment]
thanks @rjrudin!
