### ISSUE TITLE
PutMarkLogicRecord does not send flowfiles to success or batch_success

### ISSUE THREAD

**Issue by dmcassel** [marklogic/nifi#116]
I'm using a PutMarkLogicRecord processor to read a flowfile with 250 Avro rows and write them as JSON records. The writes are successful (I get 250 JSON docs in MarkLogic), but the only flowfile output is sent to the "original" relationship -- nothing to either success or batch_success. 

PutMarkLogicRecord extends PutMarkLogic. [This block of code](https://github.com/marklogic/nifi/blob/master/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/PutMarkLogic.java#L275-L293) in PutMarkLogic is in the onScheduled method, which has the @OnScheduled annotation. PutMarkLogicRecord has an initializeFactories method with the @OnScheduled annotation. Maybe only one method gets called for that annotation? 

Being able to use the batch_success relationship from PutMarkLogicRecord would provide a significant performance improvement to a client (over coverting Avro to JSON and splitting). 

NiFi: 1.12.1
MarkLogic NARS: 1.9.1.5

**Comment by rjrudin** [comment]
Thanks @dmcassel  - we'll reproduce soon, and should be able to do a bugfix release for it.

**Comment by rjrudin** [comment]
This looks like the culprit:

```
java.lang.NullPointerException: null
	at org.apache.nifi.marklogic.processor.PutMarkLogic.lambda$onScheduled$1(PutMarkLogic.java:277)
```

Investigating now why that NPE is occurring.

**Comment by rjrudin** [comment]
@dmcassel  1.9.1.7 has this bug fix in it - https://github.com/marklogic/nifi/releases/tag/1.9.1.7 . Let us know too if you're looking for a release that's been tested on a more recent release of NiFi - just open a ticket if so.

**Comment by dmcassel** [comment]
My clients are using NiFi 1.11.4 or 1.12.1. I'll give this a try as soon as I can and report back if I encounter problems. Thanks for the quick response!

**Comment by vsajjanapu-equinix** [comment]
We have recently upgraded to this version 1.9.1.7 it resolved some issue but there is a continuous logging filing up the log files with below when its idle.
`o.a.n.marklogic.processor.PutMarkLogic PutMarkLogic[id=e3c16f13-017a-1000-cb2c-ffe86ef0aa30] Flushing the WriteBatcher asynchronously in case a number of documents less than batchSize are waiting to be written
2021-07-26 20:40:07,921 INFO [Timer-Driven Process Thread-9480] c.m.c.datamovement.impl.WriteBatcherImpl flushing 0 queued docs
2021-07-26 20:40:07,921 INFO [Timer-Driven Process Thread-9480] o.a.n.marklogic.processor.PutMarkLogic PutMarkLogic[id=e3c16f13-017a-1000-cb2c-ffe86ef0aa30] Calling yield() on the ProcessContext
2021-07-26 20:40:08,921 INFO [Timer-Driven Process Thread-7798] o.a.n.marklogic.processor.PutMarkLogic PutMarkLogic[id=e3c16f13-017a-1000-cb2c-ffe86ef0aa30] Flushing the WriteBatcher asynchronously in case a number of documents less than batchSize are waiting to be written
2021-07-26 20:40:08,921 INFO [Timer-Driven Process Thread-7798] c.m.c.datamovement.impl.WriteBatcherImpl flushing 0 queued docs
2021-07-26 20:40:08,921 INFO [Timer-Driven Process Thread-7798] `

**Comment by rjrudin** [comment]
We haven't tested yet on NiFi 1.12.1, only on NiFi 1.9. This is what PutML/Record does when there's no FlowFile:

- Flush any documents waiting to be written to ML (this is essential so none are left waiting to be written)
- Call "context.yield()"

The 1.9 NiFi javadocs for "yield" state the following:

"Causes the Processor not to be scheduled for some pre-configured amount of time. The duration of time for which the processor will not be scheduled is configured in the same manner as the processor's scheduling period."

I don't have NiFi handy right now, but I believe that you can configure the amount of time that the processor will yield for, which will then limit the amount of logging that you see.

**Comment by vsajjanapu-equinix** [comment]
@rjrudin thanks for quick reply. I could able control the frequency of this logging with yield property as a workaround.

**Comment by vsajjanapu-equinix** [comment]
@rjrudin this is blocking the running process for the given yield duration :)
