### ISSUE TITLE
RunFlowMarkLogic processor Capability description.

### ISSUE THREAD

**Issue by bgeorge111** [marklogic/nifi#119]
The Capability description for RunFlowMarkLogic is incorrect. 

_Run a MarkLogic Data Hub 5 flow via the Data Hub 5.2.0 Java API. This is expected to be run on non-ingestion steps, where data has already been ingested into MarkLogic. Ingestion steps depend on access to local files, which isn't a common use case for NiFi in production. Does not yet support flows converted for Hub Central usage_

The processor seems to be updated already for 5.4 and does support Hub Central format.

**Comment by rjrudin** [comment]
Fixed via #138
