### ISSUE TITLE
Logging line should probably be a debug log, not info.

### ISSUE THREAD

**Issue by ELadner** [marklogic/nifi#126]
Causes lots of repeating, non-helpful messages every second to the app log.

https://github.com/marklogic/nifi/blob/d83a7ffb2df1cb79d76df48026768252d1583cdb/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/PutMarkLogic.java#L347

**Comment by rjrudin** [comment]
That sounds fair, those lines were added when debugging #112 and ensuring that `yield` was called when expected. That bug seems to be behind us, so debug is reasonable.
