### ISSUE TITLE
Raise logging level to debug for this one as well.

### ISSUE THREAD

**Issue by ELadner** [marklogic/nifi#127]
Causes many non-helpful lines (1 per second per processor) to spam into the app log.

https://github.com/marklogic/nifi/blob/d83a7ffb2df1cb79d76df48026768252d1583cdb/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/PutMarkLogic.java#L345

**Comment by grtjn** [comment]
Could something be done about these 'flushing 0 queued docs' messages as well, it occurs whenever the above and the one from #126 passes by:

````
2022-02-21 13:57:53,395 INFO [Timer-Driven Process Thread-3] c.m.c.datamovement.impl.WriteBatcherImpl flushing 0 queued docs
```

**Comment by grtjn** [comment]
Temporary workaround, add these lines to nifi/conf/logback.xml:

```
    <!-- Solve app log overload due to excessive logging caused by PutMarkLogic -->
    <logger name="org.apache.nifi.marklogic.processor.PutMarkLogic" level="WARN"/>
    <logger name="com.marklogic.client.datamovement.impl.WriteBatcherImpl" level="WARN"/>
```

**Comment by rjrudin** [comment]
I agree about debug for the first line. @grtjn What you did for the WriteBatcherImpl logging is the appropriate choice. I think what would be better is an issue in java-client-api for changing that particular message to debug when the number of flushed documents is zero, which of course is not very interesting. :)
