### ISSUE TITLE
Adding support for Nifi Expression language in properties

### ISSUE THREAD

**Issue by peetkes** [marklogic/nifi#13]
I would like to be able to use parameters in the properties for the MarkLogic processors.
eg: define some attribute EventName and use that in a custom property with name 'trans:event-name' and value ${EventName}

**Comment by ryanjdew** [comment]
What scope of values do you wish to have access to? We can add expression language with context properties available easily.

If you want access to flowfile properties, the WriteBatcher doesn't allow per document control of the transform parameters. If you have a set list of possible EventName values, you may want to use the RouteOnAttribute processor and route to the appropriate PutMarkLogic processor. 

https://community.hortonworks.com/questions/139243/nifiusing-routeoncontent-for-filtering-responses.html

**Comment by peetkes** [comment]
I have flow attributes for entity name flow name etc which i would like to use in parameters trans:... properties

**Comment by peetkes** [comment]
With the latest addition of DHF5.0 I would like to be able to construct also the trans:options parameter that will consist a json object.
What I would like to be able to do is something like this:
````
trans:options={"filename": "${filename}", "someProperty":"${some expression in Expression language}
````
Now I can only pick something from the Variable Registry only which is not sufficient

**Comment by rjrudin** [comment]
Closing this, as https://github.com/marklogic/java-client-api/issues/1039 was closed and thus the ServerTransform cannot be modified on a per-batch or per-document basis.
