### ISSUE TITLE
marklogicnar.version should be 1.15.3.1

### ISSUE THREAD

**Issue by hansenmc** [marklogic/nifi#135]
Shouldn't the marklogicnar.version = 1.15.3.1? 

https://github.com/marklogic/nifi/blob/f83fc15351d8b47732c90a8fa3a8bbd3ed3a44bc/pom.xml#L35

I tried building the project, and the submodules failed to resolve because they were looking for 1.15.3 versions. When I changed that peroperty in the top level pom.xml, everything built and were packaged.

When I unzip the https://github.com/marklogic/nifi/releases/download/marklogic-1.15.3.1/nifi-marklogic-nar-1.15.3.1.nar and look at the jars under META-INF/bundled-dependencies/nifi-marklogic*.jar, they are all *-1.15.3.jar instead of *-1.15.3.1.jar.

However, under META-INF/maven/org.apache.nifi/nifi-marklogic-nar/pom.xml, the marklogic submodules use the variable ${marklogicnar.version} and the pom.properties has the `value=1.15.3.1`

**Comment by rjrudin** [comment]
Fixed by #136
