### ISSUE TITLE
Query Marklogic processor Nifi

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic/nifi#15]
I recently downloaded MarkLogic nars and I don't see the URIs query property on the processor anymore.

How do I specify my search criteria for the list of URI's to retrieve?

**Comment by ryanjdew** [comment]
The latest QueryMarkLogic processor allows for more complex queries. See https://marklogic.github.io/nifi/nifi-features#querymarklogic-processor for the details on the Query and Query Type properties. 

As for keeping state, there isn't anything at the moment. We will need to determine how to best approach for this, as MarkLogic requires range indexes for Greater Than/Less Than comparisons and it can have a variety of range index types (element, JSON property, path, etc.)

**Comment by rohitshrivastava04** [comment]
Is there any system property of the document that is maintained by MarkLogic for every document which can be used to fetch incremental documents (e.g. lastupdatedon / createdon), considering we store the state outside somewhere?

**Comment by rjrudin** [comment]
For the last question - ML doesn't update the document unless it's instructed to do so. 

Closing this ticket as it involves a few different questions, each of which I believe have been answered.
