### ISSUE TITLE
queryML (and other controllers) do not pass flowFile attributes downstream

### ISSUE THREAD

**Issue by DavidEnnis-17llamas** [marklogic/nifi#150]
It appears that queryML does not pass flowFile Attribues downstream.  This seems to be verified in the code where the use is flowFile.create() rather than flowfile.clone() os something similiar.

This is a considerable item.  If one needs to keep state information (Flow Attributes) from before the QueryML step, thn the process is as follows:
 - serialize all attributes to JSON
 - store them in a cache
 [then use queryML]
 - retrieve from cache
 - re-constitute flow attributes from cached JSON
 
 Having to use 4 processor steps to save state diminishes the value of the use of the queryML controller.  My current solution is to actually use the eval endpoint and transport a JSON payload through the call and back out as part of my request and response.
 
 The Desired result would be for flow-file attributes to be passed downstream by default or configuration.

**Comment by rjrudin** [comment]
This is likely going to become several internal JIRA tickets, one per query-related controller. The goal will be establishing as much consistency in behavior as possible without introducing any breaking changes. Those changes will be identified in GitHub before the next release.

**Comment by rjrudin** [comment]
@DavidEnnis-17llamas I am closing this in favor of #161, which addresses multiple inconsistencies, including the one you highlighted here. Please look over #161 and add comments if any of the changes within it seem undesirable.
