### ISSUE TITLE
Modify NiFi Features docs page to primarily refer to inline docs

### ISSUE THREAD

**Issue by rjrudin** [marklogic/nifi#153]
The docs page on NiFi Features - https://marklogic.github.io/nifi/nifi-features - is almost entirely duplicating the inline docs available with NiFi for each component of the connector. It is expected that the docs are not in sync with the code, which means that what the user reads in the docs may not match what's shown in NiFi. 

The inline docs of controller services and processors, powered by code, is a real strength of NiFi. It allows a user to access docs at the exact point of when they use a feature. 

The NiFi Features page can still have value for a new user in providing an overview of the components that are available. That could simply be a list of each controller service and processor and then a copy/paste of the description of each. Properties/relationships would all be better described in the inline docs. 

To make this change, we'd need to ensure that we don't lose any information that's in the docs that is not yet in the inline docs. But we'd likely want to do that regardless, since a user seems far more likely to go with what's in the inline docs vs at our docs website.

**Comment by rjrudin** [comment]
@dmcassel @17llamas Let me know what you think about this change. I am expecting that most users make heavy use of the inline docs in NiFi and rarely, if ever, go to the docs website mentioned above.

**Comment by DavidEnnis-17llamas** [comment]
> @dmcassel @17llamas Let me know what you think about this change. I am expecting that most users make heavy use of the inline docs in NiFi and rarely, if ever, go to the docs website mentioned above.

Personally, I prefer a single book of record for official docs. Supporting information can be fine (but clearly supporting information and not meant to be API docs).

MarkLogic NiFi is a good example:
- Some ML inline docs driving the NiFi interface are thin.
- But then some documentation on the website is out of date or simply a mirror of the inline docs.

For NiFi, I agree - make clear and robust documentation in the controllers(driven by inline docs) that can be used without 
 necessarily needing external references.   However, if you are to do this, I think it's important to further refine the inline docs.  

An example: ExecuteScriptMarkLogic 
- has a property to skip the first result
- but also has a relationship "first result"
-- for me, this is all confusing. 
---- First off, why give an option for skip result if I am executing arbitrary code..? I can just suppress the first record in my code, if need be.
-- But then: If I skip the first result. I still have a result-set 

In this case, how the use of "skip first result" property affects the "first result" relationship can be clearly determined by the generated docs for the property. It does not end up in either relationship (fully skipped). However, how the relationships work when _not_ skipping is not clear.

Looking at the relationships, if I do *not* skip first result, and I have a set of 8 records, does my relationship usage end up as 
first: 1  - results: 6  -  last: 1 = 8
OR
first: 1 -results: 8  - last: 1 = full set to results and copy to first/last

This is where I would expect online docs to perhaps go further. - but it does not. So it's off to the code.

**Comment by rjrudin** [comment]
The "NiFi Features" page will be updated in 1.16.3.2 to briefly describe the components and refer the user to the "View Usage" feature for each processor, which provides visibility to everything that's been documented via code. 

For the comment above - providing better examples will be a separate effort.

**Comment by DavidEnnis-17llamas** [comment]
> The "NiFi Features" page will be updated in 1.16.3.2 to briefly describe the components and refer the user to the "View Usage" feature for each processor, which provides visibility to everything that's been documented via code.
> 
> For the comment above - providing better examples will be a separate effort.

Great news! Thanks
