### ISSUE TITLE
Adding Semantic Triples with Nifi

### ISSUE THREAD

**Issue by scarton** [marklogic/nifi#16]
Not an issue really, but can the put processor be used to add RDF triples (or other formats) to ML? If so, how is that set up in the configurations?

**Comment by rjrudin** [comment]
Managed triple documents can be added via PutMarkLogic. For adding triples to existing documents - that can be done in a variety of ways, but I would generally recommend using ExtensionCallMarkLogic to call a custom endpoint that has the logic for doing this.
