### ISSUE TITLE
Consistency improvements for query processors

### ISSUE THREAD

**Issue by rjrudin** [marklogic/nifi#161]
The 7 processors that perform queries against MarkLogic and do something with the results all have differences in how they behave. This can only produce confusion for users who reasonably would expect certain aspects of the processors to behave in the same way. This ticket summarizes the changes that will be made to each processor to improve the consistency of behavior while preserving backwards compatibility (though some of these changes are regarded as bug fixes and thus will result in a change in behavior that is presumed to be incorrect).

Generally, the following behavior is desired from a processor that performs a query:

1. It should not require a `FlowFile` in order to run, as it's expected that a query processor is a useful starting point for a flow
2. For any new `FlowFile`s that it creates based on results from the query, they should be created off the incoming `FlowFile`, or a newly created `FlowFile` if an incoming one does not exist
3. The incoming `FlowFile`, or a new one if it does not exist, should be sent to the "Original" relationship. It should include new "marklogic-"-prefixed attributes that provide information about the query that was executed. For example, `QueryMarkLogic` should include the query that was run and `ExecuteScriptMarkLogic` should include the script or module path that was invoked.
4. For processors that receives batches of results (i.e. that use `QueryBatcher` under the hood), if an error occurs in processing a batch, a new `FlowFile` should be created (using the original `FlowFile`) for each item in the failed batch and sent to the "Failure" relationship with information about the error.
5. For processors that make a single call to MarkLogic, a try/catch should be used around the entire operation and if any exception occurs, the original or newly-created `FlowFile` should be sent to the "Failure" relationship with information about the error.

Based on the above, the following processors will be modified:

## QueryMarkLogic

1. New FlowFiles will be created from the original one
2. `onQueryFailure` will send a new FlowFile (created from the original one) that capture the error and as much detail as possible from the `QueryFailureException`
3. While processing a batch of URIs, if an error occurs for a given URI, create a FlowFile for it (from the original one) and send it to Failure (these are being dropped on the floor right now)
4. Capture the query and query state as new attributes on the FlowFile sent to "Original"

## ApplyTransformMarkLogic

1. Send the original FlowFile to the "Original" relationship
2. Create new FlowFiles from the original FlowFile
3. When a failure occurs in a batch for a particular URI, the new FlowFile needs to be cloned from the original FlowFile

## DeleteMarkLogic

1. FlowFiles created for each deleted URI need to be created from original FlowFile
2. FlowFiles created for each URI in a failed batch need to be created from original FlowFile

## ExecuteScriptMarkLogic

1. Should be runnable without an incoming FlowFile so it can be used at the start of a flow
2. Add the script body / module path as a new attribute to the FlowFile sent to "Original"

## QueryRowsMarkLogic

1. Send incoming FlowFile to "Original" (this is currently and incorrectly ignored; will need to make this auto-terminate by default to not break existing instances of this processor)
2. Will create new FlowFile (from original FlowFile) with the output and send to "Success" (this is a change in behavior, as the original FlowFile goes to Success today; this is being treated as a bugfix though because it is blowing away the content of the incoming FlowFile, which is inconsistent with the other processors and likely unexpected for users)
3. Will include the Optic plan as an attribute on the "Original" FlowFile
4. On failure, will create a new FlowFile from the original and send it to Failure (this is also a change in behavior but is being considered a bug fix; the same behavior was changed in QueryMarkLogic in 1.16.3.1)

**Comment by DavidEnnis-17llamas** [comment]
HI Rob.

Looks good.  A few comments:

Can I interpret this phrase:
"For any new FlowFiles that it creates based on results from the query, they should be created off the incoming FlowFile, or a newly created FlowFile if an incoming one does not exist"

To mean:
"For any new FlowFiles that it creates based on results from the query, they should be created off the incoming FlowFile -**preserving existing flow attributes**, or a newly created FlowFile if an incoming one does not exist"

Second item:
Unfortunately, the exact item is lost in my head somewhere. But I think there is one more consideration on the refactoring of each item in terms of standardizing behavior.  That is: which REST API query parameters can be set.   Perhaps this is not for now and could be enhancements for the future, but I do remember recently using executeScript and returning an optic result  instead of queryRows because some needed query parameter was no exposed via queryRows.  This is a difficult one: perhaps by design, implementation details (like the REST API itself) is not meant to be exposed to the end NiFi user. In that case, the separation makes more sense.

**Comment by rjrudin** [comment]
@DavidEnnis-17llamas That's correct about the behavior - "preserving existing flow attributes", that's really the main fix here across these processors. 

Re `QueryRowsMarkLogic` - I'm going to have a separate issue to make some improvements to that as `/v1/rows` supports a number of new things that aren't yet covered by this processor.

**Comment by DavidEnnis-17llamas** [comment]
@rjrudin  Thanks. This sounds perfect.

**Comment by dmcassel** [comment]
Of the listed processors, I've used `ExecuteScriptMarkLogic` the most. I think your proposed changes there sound good. 

There are some processors that take a single flow file as input and produce zero or more flow files as a result. I like that you're capturing the need to preserve attributes. For example, if I run an `ExecuteScriptMarkLogic` processor that produced 10 flow files (based on returning a `Sequence`), each of the 10 should have the same inputs as the source flow file (if any). 

Similarly, there are processors that can group together a set of input flow files to produce a single output, as happens with `PutMarkLogic` when looking at the `BATCH_SUCCESS` relationship. Would it be practical to preserve common attributes for the batch success flow file? As an example, consider a flow that runs every 2 hours, taking about 10 minutes to complete. The flow starts with a single flow file, which prompts a query that leads to more flow files. If there is some action to be taken when the flow is complete, we use the Wait/Notify pattern and often include a timestamp for the run in the Wait/Notify key. The original flow file will be created with that timestamp, but it is not preserved in the `PutMarkLogic` batch success flow files.

**Comment by DavidEnnis-17llamas** [comment]
HI.  Sorry for the delay.  I would just think that the same patterns as other many-to-1 processors use.  Following the same pattern as MergeContent, perhaps:
 - option to keep define attribute strategy
 - destination for all original files  (and therefore with their attributes intact).
 
 https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-standard-nar/1.17.0/org.apache.nifi.processors.standard.MergeContent/
