### ISSUE TITLE
Document dynamic properties in PutMarkLogic

### ISSUE THREAD

**Issue by dmcassel** [marklogic/nifi#174]
The documentation for PutMarkLogic lists `trans:` for dynamic properties, but does not show `property:` or `meta:`. [The code](https://github.com/marklogic/nifi/blob/master/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/PutMarkLogic.java#L66-L71) shows that these capabilities are present (and have been for a couple years). It would be useful to show the capabilities.

**Comment by rjrudin** [comment]
@dmcassel I'm searching around, and I don't see any way yet for dynamic properties to appear in the processor in NiFi without the user first entering one. For example, if I add "trans:test", then a description icon will appear for it with a description that's from the marklogic/nifi code. That's good, but a user would first have to know about the "trans:" prefix, and I can't figure out how a user would know about that without having to consult external docs. Hoping to find a way to inform the user of this within the processor itself. 

Using the processor-level description is a possibility, though that description is only visible when choosing a processor to add to the canvas. It can't be seen once a processor has been added.

**Comment by rjrudin** [comment]
@dmcassel Answered my question - NiFI has a "View usage" feature that is available by right-clicking on any processor - see https://nifi.apache.org/docs/nifi-docs/html/developer-guide.html#advanced-documentation . That shows all dynamic properties. 

I have been thinking it would be better for all docs on a processor to be available within NiFi as opposed to pointing a user to external docs - namely at https://marklogic.github.io/nifi/nifi-features . I'd like for that page to instead list the various processors with a brief description and then instruct the user to view the docs for each processor available within NiFi. That allows for the vast majority of the docs to be driven by code.

Thoughts on that approach?

**Comment by dmcassel** [comment]
Hi @rjrudin. Sorry for the delayed response. Yes, adding to the "View usage" sounds good. That makes the ability to pass dynamic properties visible. Thanks for completing this!
