### ISSUE TITLE
Publish NARs in Maven

### ISSUE THREAD

**Issue by dmcassel** [marklogic/nifi#206]
I'm building something that would be a lot easier if I could set up a maven dependency on the nifi-marklogic-services-api-nar. Could we get that published in either Maven Central or http://developer.marklogic.com/maven2?

**Comment by dmcassel** [comment]
I just revised my approach so that I won't need this after all. Still, it could be helpful.

**Comment by rjrudin** [comment]
@dmcassel  What exactly were you looking to reuse? This looks doable, though we'd need to publish not just the nars but all the jars as well. Which takes awhile (hours of waiting) to do with Maven Central.

**Comment by rjrudin** [comment]
Closing for now but will continue to use for conversation as needed.

**Comment by dmcassel** [comment]
@rjrudin I was working on a custom NiFi processor that was going to use some types from the MarkLogic NARs. We revised our approach and no longer have that dependency, so the need has gone away.

**Comment by rjrudin** [comment]
Got it - would the "processors" jar have likely been sufficient then, as opposed to the nar file(s)?

**Comment by dmcassel** [comment]
> Got it - would the "processors" jar have likely been sufficient then, as opposed to the nar file(s)?

Yes, I think so.
