### ISSUE TITLE
View cookbook recipe for ingesting CSV data into ML

### ISSUE THREAD

**Issue by rjrudin** [marklogic/nifi#34]
As an ML customer and someone new to NiFi
I want to view a cookbook recipe for ingesting CSV data into ML
So that I can quickly create a flow for ingesting CSV data and do essentially everything I could with mlcp as well

- New recipe should be under https://marklogic.github.io/nifi/cookbook-recipes
- I think a title of "Ingest CSV data into MarkLogic" would work, or possibly "Ingest delimited data into MarkLogic"
- Sounds like the main recipe should be GetFile -> (optional) SplitText -> PutMarkLogicRecord with a CSVReader (not sure what the RecordWriter should be yet)
- Ideally this has an example that uses a publicly available delimited file

**Comment by millerbill3** [comment]
In addition to the above comment/user story, it will most likely be necessary to include some sort of schema in order for the CSV record to be correctly converted/translated. One option to be explored is using the InferAvroSchema processor. This should allow a simplistic schema to be inferred from the incoming CSV data.

**Comment by rjrudin** [comment]
Got two approaches working with PutMarkLogicRecord - documenting both below. The approaches are both GetFile -> SplitText -> PutMarkLogicRecord, with the second one adding a processor for inferring an Avro schema, while the first uses a user-provided schema. The inferred one is better if it produces a schema that works for your data - i.e. everything gets ingested the way you want. Otherwise, you have to provide a schema yourself. 

One way to make a schema is to use LogAttribute after InferAvroSchema to see what was inferred. Copy/paste that locally, and then change it as needed, and then use the first approach. 

Also, the PutMarkLogicRecord config is the same for each approach, so it's only described in the first approach.

** With a schema

1. GetFile - nothing special, configure the input directory as needed
1. SplitText - pick a Line Split Count that works for your CSV file - anything from 100 to 1000 should be reasonable. Also configure Header Line Count based on whether your file has a header or not.
1. PutMarkLogicRecord - configure the DatabaseClientService, and pick a suitable batch size and thread count (the default is 3; consider N * M, where N = the number of hosts, and M = the number of threads for the app server that you connect to; so for a 3 host cluster with a default of 32 threads for the app server, pick 96). See below for the Record Reader and Record Writer.

For the Record Reader - add a CSVReader controller service with the following config:

- For Schema Access Strategy, select "Use 'Schema Text' Property"
- For Schema Text, paste in your Avro schema
- Make sure Treat First Line As Header is configured correctly, along with the Value Separator and Quote Character
- Pay special attention to the Escape Character - ensure that if it exists in your CSV file, it's used properly as an escape character (e.g. for double quotes within double quotes)

For the Record Writer - add a JsonRecordSetWriter controller service with the following config:

- Schema Write Strategy = "Do Not Write Schema" 
- Schema Access Strategy = "Inherit Record Schema"
- Schema Text = "${inferred.avro.schema}"

**Comment by rjrudin** [comment]
Pinging @fsnow about this. I'll be adding a concrete example with a couple templates soon.

**Comment by rjrudin** [comment]
See the attached zip for an example of a user-defined schema and sample data (it's traffic stop data with no PII in it). The user-defined schema is resulting in some columns not being processed yet, like DateOfStop and TimeOfStop - not sure what's up there yet, going to fiddle with it more. But otherwise it's a working example - the sample file can be dumped into the directory watched by GetFile, and it'll ingest 15k traffic documents. 

[traffic.zip](https://github.com/marklogic/nifi/files/2741760/traffic.zip)

**Comment by rjrudin** [comment]
See the attached zip for an example of an inferred schema and sample data (a publicly available list of US zip codes). Same as above - unzip this, upload the template into NiFi, and then dump the zip code file into the directory watched by GetFile, and it'll ingest just over 40k zip code documents. 

Note - after uploading the template, be sure to enable the 3 controller services and to configure the DocumentsDatabaseClient service correctly for your ML server. 

[zipcodes.zip](https://github.com/marklogic/nifi/files/2741763/zipcodes.zip)

**Comment by ryanjdew** [comment]
@rjrudin would you feel comfortable adding a Markdown file via a PR against the docs-next branch? 

You could see other cookbook pagess at https://github.com/marklogic/nifi/tree/docs-next/_pages/cookbooks for reference.

**Comment by rjrudin** [comment]
Sure, I'll take a crack at it. Is it okay to include the sample files?

**Comment by aajacobs** [comment]
Is there an ETA for this recipe being published?

**Comment by ehennum** [comment]
As a head's up, the 4.2.0 Java API (to be released soon, concurrently with MarkLogic 9.0-9) will provide a CSV splitter that converts the CSV data rows to JSON documents that can be written using DMSDK.
