### ISSUE TITLE
Flush async instead of wait in PutMarkLogicRecord?

### ISSUE THREAD

**Issue by rjrudin** [marklogic/nifi#38]
I noticed in the "finally" block of PutMarkLogicRecord's onTrigger method, there's a call to flushAndWait:

```
if (!error) {
                DatabaseClient client = getDatabaseClient(context);
                String url = client != null
                        ? client.getHost() + ":" + client.getPort()
                        : "MarkLogic cluster";
                writeBatcher.flushAndWait();
                session.getProvenanceReporter().send(flowFile, url, String.format("Added %d documents to MarkLogic.", added));
                session.transfer(flowFile, ORIGINAL);
                uriFlowFileMap.remove(flowFile.getAttribute(CoreAttributes.UUID.key()));
                getLogger().info("Inserted {} records into MarkLogic", new Object[]{ added });
```

This seems safe to turn into a non-blocking flushAsync call instead. I don't think any of the code that comes after it cares about the WriteBatcher finishing its flush call.

**Comment by ryanjdew** [comment]
@rjrudin I don't have a passionate stance behind the flushAndWait here. In NiFi there is a setting that stops concurrent execution of processors and my thinking was that using flushAsync could technically cause work to be done after the next call to the processor. Also, you could potentially have the provenance in NiFi reporting records written before they actually are.

Not things I feel too strongly about, especially if there is a good reason to think there is a considerable performance impact.

**Comment by rjrudin** [comment]
No action for now then.
