### ISSUE TITLE
Binary data format on ingestion into Marklogic

### ISSUE THREAD

**Issue by dhillon21** [marklogic/nifi#47]
I am attempting to ingest a csv file into Marklogic using NiFi.

When I do not specify the file format of ingestion it is stored as a binary.

However if I do specify a format, ie JSON it fails on the putmarklogic step.

Is this a limitation of the NiFi processor or am I configuring the processor incorrectly?

**Comment by yasht2010** [comment]
It might be useful to check out this GitHub [issue](https://github.com/marklogic/nifi/issues/34) and this [comment](https://github.com/marklogic/nifi/issues/34#issuecomment-452546949) -  for ingesting CSV files into MarkLogic using NiFi. We are working on an easy to follow recipe for this which we will publish here - https://marklogic.github.io/nifi/

**Comment by dhillon21** [comment]
Thanks this came in very handy!

However I have a supplemental issue occurring now.  When trying to pass a csv file that has headers as such "PatientInfo/Person/FirstName", I get a DataSetException error during the 'InferAvroSchema' processor saying - "Bad Header for field, must start with a character or _"

I am using the '/' character to set headers appropriately.  Is there a specific configuration that needs to be done in the processor to allow for this?

**Comment by rjrudin** [comment]
InferAvroSchema is fairly particular about what CSV must look like. You might be better off creating your own Avro schema that defines everything so that you don't have to deal with InferAvroSchema's constraints.

**Comment by dhillon21** [comment]
I am completely new to Avro is there a good reference to creating a schema for csv?

**Comment by rjrudin** [comment]
See my comments in https://github.com/marklogic/nifi/issues/34 - I'm new to it as well, and the way I made something that worked for my data was to use InferAvroSchema and get it to work once (no matter how much I had to change my data) and then sent the FlowFile to a LogAttribute, which logged the inferred schema, I think under an "inferred.avro.schema" attribute. I used that as a starting point (was about 90% correct) to come up with something that worked for my data.

**Comment by rjrudin** [comment]
Closing, as question seems to have been answered.
