### ISSUE TITLE
Allow for variable expressions on DatabaseClientService properties

### ISSUE THREAD

**Issue by rjrudin** [marklogic/nifi#53]
The following DatabaseClientService properties should support expressions using process group variables. This allows for all environment-based values for a process group to be centralized as variables.

- host
- port
- load balancer
- security context type
- username (not password though, since variables can't be made sensitive)
- database
- external name
- client auth

**Comment by rjrudin** [comment]
Addressed by https://github.com/marklogic-community/marklogic-nifi-incubator/pull/6

**Comment by peetkes** [comment]
This is basically the same question I asked last year! See https://github.com/marklogic/nifi/issues/13

**Comment by rjrudin** [comment]
This will be in the 1.9.1.5 release, as it was inherited from the incubator project.
