### ISSUE TITLE
new PutMarklogicRecordProcessor is not documented

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/nifi#58]
I did not find any mention of this processor in our docs. 

All processors should really be documented.

In particular, use in hub ingest at https://marklogic.github.io/nifi/run-data-hub-input-flow should probably be changed to use this processor.

**Comment by rjrudin** [comment]
All processors are listed under https://marklogic.github.io/nifi/nifi-features , but the title of that link doesn't really suggest that it has a list of all the processors.

**Comment by rjrudin** [comment]
Closing this since PutMarkLogicRecord is documented at https://marklogic.github.io/nifi/nifi-features . A separate ticket should be used to suggest how to better organize the documentation.
