### ISSUE TITLE
Document required privileges

### ISSUE THREAD

**Issue by dmcassel** [marklogic/nifi#65]
For each processor, please add the list of privileges required. For example, `ExecuteScriptMarkLogic` needs (at least) `http://marklogic.com/xdmp/privileges/xdbc-eval`. A complete list would make secure deployments a lot easier.

**Comment by rjrudin** [comment]
Tagging this as documentation, but we may choose to document this within the processor annotations so it's available within NiFi.

**Comment by rjrudin** [comment]
Resolving in 1.16.3.2 via #65 . The description of each processor now mentions the minimum set of privileges. Each IT test has been enhanced to use a user with the minimum set of privileges. And any IT test running as the "admin" user will now fail.
