### ISSUE TITLE
QueryMarkLogic doesn't use cts query in Combined Query

### ISSUE THREAD

**Issue by chamlin** [marklogic/nifi#66]
The page https://marklogic.github.io/nifi/step-by-step has, under 'Add QueryMarkLogic Processor' a 'Combined Query (XML)'.  A cts:query like this does work as shown, but this isn't a combined query.  

If I switch to a combined query version

```xml
<search xmlns="http://marklogic.com/appservices/search">
    <cts:collection-query xmlns:cts="http://marklogic.com/cts">
      <cts:uri>iot-data</cts:uri>
    </cts:collection-query>
</search>
```

to match the syntax at http://docs.marklogic.com/guide/rest-dev/search#id_84389 then it appears that all documents are selected; that is, the cts:query is not used to limit the matches.

**Comment by ehennum** [comment]
I would suggest that the immediate fix is to the documentation.

We can consider separately whether it is important to support combined query.  Given that a combined query requires transformation, the case can be made that it's a better practice anyway to send a top-level cts.query and thus avoid the cost of transforming the query on each request.

**Comment by chamlin** [comment]
I should also note that the QueryMarkLogic menu for query type lists Combined Query.

**Comment by kmoralesml** [comment]
Thank you both for considering this issue.
I vote for this suggestion : "the case can be made that it's a better practice anyway to send a top-level cts.query"

**Comment by ehennum** [comment]
@kmoralesml , does the current QueryMarkLogic processor work when sent:

    <cts:collection-query xmlns:cts="http://marklogic.com/cts">
      <cts:uri>iot-data</cts:uri>
    </cts:collection-query>

If so, the best practice is already supported and doesn't require any code changes.

In that case, the action item would be to fix the documentation and suggest the best practice.

**Comment by kmoralesml** [comment]
@ehennum 
Yes.  I confirmed that the following works **provided** customer upgrade to ML 9.0-8 or higher.  ML 9.0-5, -4 does not work.
Given: ML 9.0-8 or higher, NiFi QueryProcessor 1.8.0.3, Query Type is Combined Query XML.
When: Query Value
<cts:collection-query xmlns:cts="http://marklogic.com/cts">
<cts:uri>somecollname</cts:uri>
</cts:collection-query>

Then: it works.

The step-by-step guide/documentation indeed needs to be fixed.  As Chris said, the example and the fact it says Combined Query is confusing.

**Comment by ehennum** [comment]
Hmmm.  In the docs branch, the "combined query" example already shows a CTS query.

I will ping Ryan about how the GitHub pages get built from the docs branch.

**Comment by ehennum** [comment]
Never mind. I see that I misread the issue -- the problem is in the name, not in the documented example.

**Comment by ehennum** [comment]
Okay, the documentation fixup has rippled through to the GitHub pages.

Longer term, it would be good to fix the query type in the QueryMarkLogic processor, but that's better taken up with other fixes to the procesors.

**Comment by rjrudin** [comment]
Added tests to cover both real combined queries and serialized queries. The processor description states that both are supported. It would likely be better for the long term to have "Serialized CTS Query" as its own option so it's more obvious that it's supported.
