### ISSUE TITLE
Breaking change on update

### ISSUE THREAD

**Issue by chamlin** [marklogic/nifi#71]
Reported breaking change, would be good to document?
======
When migrating our template from Nifi 1.7 to 1.9 the PutMarkLogic NAR was automatically updated from PutMarkLogic 1.8.0-SNAPSHOT to PutMarkLogic 1.8.0.3.

The PutMarkLogic NiFi Processor 1.8.03 created a property called  "URI Attribute Name", in the previous version,  this was a custom property (URI attribute name with value uri).  During the update, the URI Attribute Name was given a default value UUID, while the custom property remained in the list of properties.  The new "URI Attribute Name" needed to be updated with the correct value to function properly.

This appears to be a general compatibility issue with updating the MarkLogic NARs and may affect others upgrading.

**Comment by rjrudin** [comment]
This is a fair request, though I think the ship has sailed at this point. 

I think what we need to do at some point is decouple our version numbers from NiFI version numbers so that we can do an e.g. 2.0 release that has breaking changes in it. Pinging @yasht2010 .
