### ISSUE TITLE
NullPointerException on ExtensionCallMarklogic for PUT and DELETE

### ISSUE THREAD

**Issue by ltnd** [marklogic/nifi#73]
When doing a ExtensionCallMarklogic on a Rest Extension service (which does nothing) with no payload for PUT and DELETE => java.lang.NullPointerException

On ML side, the status is 200 (OK).

**Comment by rjrudin** [comment]
There's a fix for this in the incubator project, but I didn't see any tests for it. So adding tests as part of this ticket.

**Comment by rjrudin** [comment]
Note that I was not able to reproduce this for a DELETE. This may be due to the connector now using 5.3.2. of the Java Client, which requires a non-null input for a PUT, but not for a DELETE.
