### ISSUE TITLE
QueryMarkLogic 1.8.0.3 returns (total - total mod batch size) number of files

### ISSUE THREAD

**Issue by julianwang90** [marklogic/nifi#75]
## Description
When using the QueryMarkLogic 1.8.0.3 processor to return URIs of documents matching both a "sample" and "latest" collection from a bitemporal FINAL database, the component will return (total - total mod batch size) number of files. Ie, if batch size is set to 300, and there are 700 documents, then the processor will only return 600 URIs, leaving the remaining 100. 

If a second flowfile is created through GenerateFlowFile processor to re-run the query, for instances when number of total files < batch size, the QueryMarkLogic processor will simply not process anything or give any outputs, leaving that flowfile stuck in the queue upstream of the processor.

## Flow overview
![image](https://user-images.githubusercontent.com/10420515/66123178-50eec500-e5d9-11e9-969a-220a8f1fadfd.png)

### QueryMarkLogic processor configuration
![image](https://user-images.githubusercontent.com/10420515/66123103-2f8dd900-e5d9-11e9-9187-e611a8136a0a.png)

### QueryMarkLogic processor query
`<cts:and-query xmlns:cts="http://marklogic.com/cts">
    <cts:collection-query xmlns:cts="http://marklogic.com/cts">
        <cts:uri>${soft_delete_collection:toString()}</cts:uri>
    </cts:collection-query>
    <cts:collection-query xmlns:cts="http://marklogic.com/cts">
        <cts:uri>${latest_collection:toString()}</cts:uri>
    </cts:collection-query>
</cts:and-query>`

**Comment by sharmad1** [comment]
[Defect_Recording.zip](https://github.com/marklogic/nifi/files/3685930/Defect_Recording.zip)

**Comment by rjrudin** [comment]
I believe this is the same as #91 . Both QueryML and DeleteML were throwing an error the first time session.commit() was called due to the incoming FlowFile not having been routed to a destination relationship. That has been fixed in #91 , such that the incoming FF (if not null) will be routed to an "original" relationship.
