### ISSUE TITLE
ExtensionCallMarkLogic passes harmonisation batches even if they contain errors

### ISSUE THREAD

**Issue by julianwang90** [marklogic/nifi#77]
# Description
When using ExtensionCallMarkLogic 1.8.0.3 processor to harmonise batches of URIs, the resulting response flowfile is directed to the success flow even if the batch contains errors. The expected behaviour for batch responses which containing errors would be for them to be directed to the failure flow.

## Successful batch harmonisation response
`{"totalCount":7, "errorCount":0, "completedItems":["/entities/ACTIONS.csv-6", "/entities/ACTIONS.csv-1", "/entities/ACTIONS.csv-3", "/entities/ACTIONS.csv-7", "/entities/ACTIONS.csv-5", "/entities/ACTIONS.csv-4", "/entities/ACTIONS.csv-2"], "failedItems":[], "errors":[]}`

## Errors within batch response
`{"totalCount":7, "errorCount":1, "completedItems"......... etc}`

**Comment by rjrudin** [comment]
@julianwang90  This is outside the scope of ExtensionCallML. That processor can't be expected to know how to interpret a DHF-specific JSON response body. It's a choice by DHF to return a 200 when errors occur, with the errors being in the response body. 

Note that #90 is a valid issue (assuming it can be reproduced), as in that scenario, ML is returning a 500, but ExtensionCallML is routing the FF to the success relationship.
