### ISSUE TITLE
Copy user-defined attributes of incoming FlowFile to outputted FlowFiles in PutMarkLogic

### ISSUE THREAD

**Issue by millerbill3** [marklogic/nifi#89]
After executing the processor, all written URIs are populated in an attribute in a new FlowFile, but the original FlowFiles attributes are lost. Suggest allowing for a user-defined comma separated list of attributes to be copied from the original FlowFile to the batch-success FlowFile

**Comment by rjrudin** [comment]
I recommend adding this to marklogic-nifi-incubator first, as I think it's more likely to be addressed via the community project.

**Comment by rjrudin** [comment]
Similar to how QueryMarkLogic will support "original" as a relationship for the incoming FlowFile in 1.9.1.5, this should support "original" as a relationship for the incoming FlowFile (if not null).

**Comment by rjrudin** [comment]
Did some testing of this and verified that the incoming FlowFiles are properly routed to the `success` relationship, while a new FlowFile is sent to the `batch_success` relationship. The latter doesn't have attributes from the former, as it wouldn't be meaningful to take all the attributes from N FlowFiles and try to add them to one new FlowFile. So I think this is working properly, though it may not have been at the time that the ticket was first created.
