### ISSUE TITLE
ExtensionCallMarkLogic sends to success when REST call responds 500

### ISSUE THREAD

**Issue by s3-4v** [marklogic/nifi#90]
I'm working with a client who experienced this apparent bug: 

Using ExtensionCallMarkLogic proc to POST to Data Hub REST extension mlRunFlow, when the response status code is 500 Internal Server Error, the FlowFile is being routed to the success relationship.

The InvokeHTTP proc making the same call to the same resource sends to failure queue and only routes to the equivalent of success when the status code is 2xx, the expected behavior.

MarkLogic 10.0-4
MarkLogic Data Hub 5.2.1
NiFi 1.11.4
MarkLogic NARS 1.9.1.3-incubator

**Comment by rjrudin** [comment]
I tried reproducing this against the latest incubator release, and when an error is thrown by a REST extension, the session is rolled back - the incoming FlowFile gets queued up and not sent anywhere. 

So while I can't reproduce the issue reported here, I don't think rolling back the session is a good user experience - the FlowFile that failed is likely to result in a 500 being thrown again. Sending that to the "failure" relationship seems like the expected result here.
